(define (fringe-version0 x)
  (let ((h (if (pair? x) (car x) x))
		(t (if (pair? x) (cdr x) x)))
	(cond ((number? x) (list x))
		  ((null? x) '())
		  ((pair? x)
		   (append (fringe-version0 h)
				   (fringe-version0 t)))
		  (else "Unexpected type Error"))))
